### PR TITLE
Auto load charts

### PR DESCRIPTION
**Pull request by WildOrangutan**
This PR basically removes `Load chart` button, and loads charts directly.

#7

### CODE REVIEW

**Comment by GabrielTavernini** [comment]
Ok, thanks. I still think that giving the option to not load charts automatically would be better. I'm going to merge the pull request into a new experimental branch and make some changes there.

**Comment by WildOrangutan** [comment]
What are your concerns regarding this?

From my preference, I mostly look at charts. Mainly to see where infection trends are going.

**Comment by GabrielTavernini** [comment]
My main concern is that older smartphones may have a hard time rendering the charts and users may prefer to not load them for a smoother experience. I myself experienced this with an old phone that I had laying around.

**Comment by WildOrangutan** [comment]
Ah I see, that's a valid point. I don't completely understand whole code, but maybe some things don't load async properly. Or there is too much chart data being displayed at once. I guess manual load button makes sense for now then, yeah.

**Pull request merged**
